version: 2

name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
 
    - name: Sample
      id: documents
      uses: itsw-circleci-test/enn-actions-test-public@master
      with:
        shellcommand: 'date' 

    - name: Checkout submodules
      shell: bash
      run: |
        cat README.md
    - name: Greeting
      env:
        MY_VAR: My name is
        FIRST_NAME: Mona
        MIDDLE_NAME: The
        LAST_NAME: Octocat
      run: |
        echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
